In [1]:

import pandas as pd
df = pd.read_csv('DataCoSupplyChainDataset.csv', encoding='ISO-8859-1')
df.info

<bound method DataFrame.info of             Type  Days for shipping (real)  Days for shipment (scheduled)  \
0          DEBIT                         3                              4
1       TRANSFER                         5                              4
2           CASH                         4                              4
3          DEBIT                         3                              4
4        PAYMENT                         2                              4
...          ...                       ...                            ...
180514      CASH                         4                              4
180515     DEBIT                         3                              2
180516  TRANSFER                         5                              4
180517   PAYMENT                         3                              4
180518   PAYMENT                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
0               91.250000          314.640015  Advance shipping
1             -249.089996          311.359985     Late delivery
2             -247.779999          309.720001  Shipping on time
3               22.860001          304.809998  Advance shipping
4              134.210007          298.250000  Advance shipping
...                   ...                 ...               ...
180514          40.000000          399.980011  Shipping on time
180515        -613.770019          395.980011     Late delivery
180516         141.110001          391.980011     Late delivery
180517         186.229996          387.980011  Advance shipping
180518         168.949997          383.980011  Shipping on time

        Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                        0           73  Sporting Goods        Caguas  ...
1                        1           73  Sporting Goods        Caguas  ...
2                        0           73  Sporting Goods      San Jose  ...
3                        0           73  Sporting Goods   Los Angeles  ...
4                        0           73  Sporting Goods        Caguas  ...
...                    ...          ...             ...           ...  ...
180514                   0           45         Fishing      Brooklyn  ...
180515                   1           45         Fishing   Bakersfield  ...
180516                   1           45         Fishing       Bristol  ...
180517                   0           45         Fishing        Caguas  ...
180518                   0           45         Fishing        Caguas  ...

       Order Zipcode Product Card Id Product Category Id  Product Description  \
0                NaN            1360                  73                  NaN
1                NaN            1360                  73                  NaN
2                NaN            1360                  73                  NaN
3                NaN            1360                  73                  NaN
4                NaN            1360                  73                  NaN
...              ...             ...                 ...                  ...
180514           NaN            1004                  45                  NaN
180515           NaN            1004                  45                  NaN
180516           NaN            1004                  45                  NaN
180517           NaN            1004                  45                  NaN
180518           NaN            1004                  45                  NaN

                                            Product Image  \
0            http://images.acmesports.sports/Smart+watch
1            http://images.acmesports.sports/Smart+watch
2            http://images.acmesports.sports/Smart+watch
3            http://images.acmesports.sports/Smart+watch
4            http://images.acmesports.sports/Smart+watch
...                                                   ...
180514  http://images.acmesports.sports/Field+%26+Stre...
180515  http://images.acmesports.sports/Field+%26+Stre...
180516  http://images.acmesports.sports/Field+%26+Stre...
180517  http://images.acmesports.sports/Field+%26+Stre...
180518  http://images.acmesports.sports/Field+%26+Stre...

                                     Product Name Product Price  \
0                                    Smart watch     327.750000
1                                    Smart watch     327.750000
2                                    Smart watch     327.750000
3                                    Smart watch     327.750000
4                                    Smart watch     327.750000
...                                           ...           ...
180514  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180515  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180516  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180517  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180518  Field & Stream Sportsman 16 Gun Fire Safe    399.980011

       Product Status shipping date (DateOrders)   Shipping Mode
0                   0             2/3/2018 22:56  Standard Class
1                   0            1/18/2018 12:27  Standard Class
2                   0            1/17/2018 12:06  Standard Class
3                   0            1/16/2018 11:45  Standard Class
4                   0            1/15/2018 11:24  Standard Class
...               ...                        ...             ...
180514              0             1/20/2016 3:40  Standard Class
180515              0             1/19/2016 1:34    Second Class
180516              0            1/20/2016 21:00  Standard Class
180517              0            1/18/2016 20:18  Standard Class
180518              0            1/19/2016 18:54  Standard Class

[180519 rows x 53 columns]>

In [2]:


countries = df['Order Country'].unique()

# print the list of countries
print(countries)

['Indonesia' 'India' 'Australia' 'China' 'Japón' 'Corea del Sur'
 'Singapur' 'Turquía' 'Mongolia' 'Estados Unidos' 'Nigeria'
 'República Democrática del Congo' 'Senegal' 'Marruecos' 'Alemania'
 'Francia' 'Países Bajos' 'Reino Unido' 'Guatemala' 'El Salvador' 'Panamá'
 'República Dominicana' 'Venezuela' 'Colombia' 'Honduras' 'Brasil'
 'México' 'Uruguay' 'Argentina' 'Cuba' 'Perú' 'Nicaragua' 'Ecuador'
 'Angola' 'Sudán' 'Somalia' 'Costa de Marfil' 'Egipto' 'Italia' 'España'
 'Suecia' 'Austria' 'Canada' 'Madagascar' 'Argelia' 'Liberia' 'Zambia'
 'Níger' 'SudAfrica' 'Mozambique' 'Tanzania' 'Ruanda' 'Israel'
 'Nueva Zelanda' 'Bangladés' 'Tailandia' 'Irak' 'Arabia Saudí' 'Filipinas'
 'Kazajistán' 'Irán' 'Myanmar (Birmania)' 'Uzbekistán' 'Benín' 'Camerún'
 'Kenia' 'Togo' 'Ucrania' 'Polonia' 'Portugal' 'Rumania'
 'Trinidad y Tobago' 'Afganistán' 'Pakistán' 'Vietnam' 'Malasia'
 'Finlandia' 'Rusia' 'Irlanda' 'Noruega' 'Eslovaquia' 'Bélgica' 'Bolivia'
 'Chile' 'Jamaica' 'Yemen' 'Ghana' 'Guinea' 'Etiopía' 'Bulgaria'
 'Kirguistán' 'Georgia' 'Nepal' 'Emiratos Árabes Unidos' 'Camboya'
 'Uganda' 'Lesoto' 'Lituania' 'Suiza' 'Hungría' 'Dinamarca' 'Haití'
 'Bielorrusia' 'Croacia' 'Laos' 'Baréin' 'Macedonia' 'República Checa'
 'Sri Lanka' 'Zimbabue' 'Eritrea' 'Burkina Faso' 'Costa Rica' 'Libia'
 'Barbados' 'Tayikistán' 'Siria' 'Guadalupe' 'Papúa Nueva Guinea'
 'Azerbaiyán' 'Turkmenistán' 'Paraguay' 'Jordania' 'Hong Kong' 'Martinica'
 'Moldavia' 'Qatar' 'Mali' 'Albania' 'República del Congo'
 'Bosnia y Herzegovina' 'Omán' 'Túnez' 'Sierra Leona' 'Yibuti' 'Burundi'
 'Montenegro' 'Gabón' 'Sudán del Sur' 'Luxemburgo' 'Namibia' 'Mauritania'
 'Grecia' 'Suazilandia' 'Guyana' 'Guayana Francesa'
 'República Centroafricana' 'Taiwán' 'Estonia' 'Líbano' 'Chipre'
 'Guinea-Bissau' 'Surinam' 'Belice' 'Eslovenia' 'República de Gambia'
 'Botsuana' 'Armenia' 'Guinea Ecuatorial' 'Kuwait' 'Bután' 'Chad' 'Serbia'
 'Sáhara Occidental']

In [3]:
country_counts = df['Order Country'].value_counts()

# set max_rows to None to print all rows
pd.set_option('display.max_rows', None)

# print the counts
print(country_counts)

Estados Unidos                     24840
Francia                            13222
México                             13172
Alemania                            9564
Australia                           8497
Brasil                              7987
Reino Unido                         7302
China                               5758
Italia                              4989
India                               4783
Indonesia                           4204
España                              3868
El Salvador                         3726
República Dominicana                3669
Honduras                            3629
Cuba                                3534
Turquía                             3395
Nicaragua                           3046
Guatemala                           2778
Nigeria                             2309
Filipinas                           2103
Panamá                              1941
Países Bajos                        1932
Argentina                           1931
Colombia                            1771
Nueva Zelanda                       1590
Irán                                1460
Austria                             1387
Egipto                              1189
Marruecos                           1135
SudAfrica                           1099
Rusia                               1014
República Democrática del Congo     1010
Venezuela                            984
Irak                                 976
Ucrania                              967
Canada                               959
Suecia                               929
Tailandia                            909
Arabia Saudí                         860
Perú                                 764
Pakistán                             758
Japón                                758
Vietnam                              757
Chile                                738
Bélgica                              664
Polonia                              641
Corea del Sur                        583
Malasia                              544
Haití                                534
Argelia                              516
Irlanda                              491
Bangladés                            466
Rumania                              455
Singapur                             455
Myanmar (Birmania)                   409
Tanzania                             378
Portugal                             343
Noruega                              333
Suiza                                330
Angola                               306
Ecuador                              294
Finlandia                            290
Dinamarca                            285
Camerún                              275
Kazajistán                           274
Zambia                               266
Israel                               265
Ghana                                264
Senegal                              263
Costa de Marfil                      257
Sudán                                251
Mozambique                           244
Kenia                                238
Bolivia                              213
Bielorrusia                          210
Zimbabue                             190
República Checa                      187
Hungría                              179
Jamaica                              170
Bulgaria                             166
Afganistán                           163
Camboya                              152
Madagascar                           149
Somalia                              141
Uruguay                              139
Trinidad y Tobago                    138
Lituania                             133
Togo                                 122
Uzbekistán                           121
Martinica                            120
Barbados                             117
Níger                                108
Jordania                             108
Libia                                105
Mali                                 103
Kirguistán                            98
Uganda                                96
Georgia                               93
Croacia                               86
Ruanda                                86
Benín                                 85
Nepal                                 80
Mongolia                              79
Paraguay                              78
Moldavia                              78
Hong Kong                             73
Yemen                                 71
Azerbaiyán                            68
Siria                                 63
Papúa Nueva Guinea                    61
Turkmenistán                          53
Guinea                                45
Bosnia y Herzegovina                  45
Gabón                                 45
Qatar                                 42
Sierra Leona                          39
Albania                               37
Costa Rica                            36
Guadalupe                             36
Túnez                                 36
Liberia                               34
Yibuti                                31
Emiratos Árabes Unidos                29
Taiwán                                29
Estonia                               29
Guinea-Bissau                         28
Grecia                                28
Etiopía                               25
República Centroafricana              23
Eslovaquia                            22
Mauritania                            21
Namibia                               20
Lesoto                                20
Líbano                                20
Guyana                                19
Sri Lanka                             16
República del Congo                   13
Belice                                13
Botsuana                              13
Chipre                                12
Montenegro                            11
Burkina Faso                          11
Luxemburgo                            10
Guayana Francesa                       9
Surinam                                8
Omán                                   8
Tayikistán                             7
Eslovenia                              6
Macedonia                              6
Laos                                   6
Suazilandia                            5
República de Gambia                    5
Sudán del Sur                          5
Armenia                                5
Bután                                  5
Baréin                                 4
Chad                                   3
Eritrea                                2
Guinea Ecuatorial                      2
Kuwait                                 2
Sáhara Occidental                      2
Burundi                                1
Serbia                                 1
Name: Order Country, dtype: int64

In [5]:
null_counts = df.isnull().sum()

# print the null counts
print(null_counts)

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64